service:
  name: signalFailure

custom:
  default_stage: dev
  
provider:
  name: aws
  region: eu-west-1
  stage: ${opt:stage, self:custom.default_stage}
  runtime: nodejs8.10
  memorySize: 128
  environment:
    SKILL_ID: ${ssm:/signalFailure/SKILL_ID~true}
    TFL_APP_KEY: ${ssm:/signalFailure/TFL_APP_KEY~true}
    TFL_APP_ID: ${ssm:/signalFailure/TFL_APP_ID~true}

package:
  exclude:
    - .babelrc
    - .git/**
    - .eslintrc.json
    - .gitignore
    - LICENCE
    - README.md
    - webpack.config.js

functions:
  handler:
    timeout: 6
    handler: index.handler
    name: signalFailure-${self:provider.stage}
    memorySize: 128
    events:
      - alexaSkill

plugins:
  - serverless-webpack
