service:
  name: signalFailure

custom:
  default_stage: dev
  optimize:
    presets:
      - - env
        - targets:
            node: '6.10'
    plugins:
      - transform-runtime
      - transform-object-rest-spread
    prefix: dist

provider:
  name: aws
  region: eu-west-1
  stage: ${opt:stage, self:custom.default_stage}
  runtime: nodejs6.10
  memorySize: 128
  environment:
    SKILL_ID: ${ssm:/signalFailure/SKILL_ID~true}
    TFL_APP_KEY: ${ssm:/signalFailure/TFL_APP_KEY~true}
    TFL_APP_ID: ${ssm:/signalFailure/TFL_APP_ID~true}

package:
  exclude:
    - .git/**
    - .eslintrc.json
    - .gitignore
    - LICENCE
    - README.md
  excludeDevDependencies: true

functions:
  handler:
    timeout: 6
    handler: index.handler
    name: signalFailure-${self:provider.stage}
    memorySize: 128
    events:
      - alexaSkill

plugins:
  - serverless-plugin-optimize
